app/config/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from config import settings
from posts import apis as posts_apis
from posts.views import tag_post_list
from members import apis as members_apis


urlpatterns_api_posts = ([
    path('post/', posts_apis.PostList.as_view(), name='posts'),
    path('post/<int:pk>/', posts_apis.PostDetail.as_view(), name='post-detail'),
    path('post/<int:post_pk>/like/', posts_apis.PostLikeCreateDestroy.as_view(), name='post-like'),

    path('postlike/', posts_apis.PostLikeCreateAPIView.as_view()),
    path('postlike/<int:pk>/', posts_apis.PostLikeDestroyAPIView.as_view()),
], 'posts')
urlpatterns_api_members = ([
    path('auth-token/', members_apis.AuthTokenView.as_view()),
    path('auth-token/facebook-auth-token/', members_apis.FacebookAuthTokenView.as_view()),
    path('user/profile/', members_apis.UserDetail.as_view()),
    path('user/<int:pk>/', members_apis.UserDetail.as_view()),
    path('user/view/profile/', members_apis.UserDetailAPIView.as_view()),
    path('user/view/<int:pk>/', members_apis.UserDetailAPIView.as_view()),
], 'members')
urlpatterns_api = ([
    path('posts/', include(urlpatterns_api_posts)),
    path('members/', include(urlpatterns_api_members)),
], 'api')

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='posts:post-list'), name='index'),
    path('admin/', admin.site.urls),
    path('posts/', include('posts.urls')),
    path('explore/tags/<str:tag_name>/', tag_post_list, name='tag-post-list'),
    path('members/', include('members.urls')),
    path('api/', include(urlpatterns_api)),
]
# MEDIA_URL로 시작하는 URL은 static()내의 serve() 함수를 통해 처리
# MEDIA_ROOT기준으로 파일을 검색함
urlpatterns += static(
    prefix=settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT,
)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

app/posts/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from . import views, apis

# 중복되는 것을 방지시켜줌
app_name = 'posts'



# config.urls에 연결되는 것이기 때문에 / 기호는 뒷쪽에 붙여주어야한다.
urlpatterns = [
    path('', views.post_list, name='post-list'),
    path('create/', views.post_create, name='post-create'),
    path('<int:post_pk>/comments/create/', views.comment_create, name='comment-create'),
    path('tag-search/', views.tag_search, name='tag-search'),
    path('<int:post_pk>/like-toggle/', views.post_like_toggle, name='post-like-toggle'),
    path('tag-search/', apis.tag_search, name='api_tag_search'),
]

app/posts/models.py
import re

from django.db import models
from django.utils import timezone

# from members.models import User
from django.conf import settings


class Post(models.Model):
    author = models.ForeignKey(
        # <AppName>.<ModelName>
        # 'members.User',
        # User,
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name='작성자'
    )
    photo = models.ImageField('사진', upload_to='post')
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        through='PostLike',
        related_name='like_posts',
        related_query_name='like_post',
    )

    class Meta:
        verbose_name = '포스트'
        verbose_name_plural = f'{verbose_name} 목록'
        ordering = ['-pk']

    def like_toggle(self, user):

        # 전달받은 user가 이 Post를 Like한다면 해제
        # 안되어있다면 Like처리
        postlike, postlike_created = self.postlike_set.get_or_create(user=user)
        if not postlike_created:
            postlike.delete()


class Comment(models.Model):
    TAG_PATTERN = re.compile(r'#(?P<tag>\w+)')
    post = models.ForeignKey(
        'Post',
        on_delete=models.CASCADE,
        verbose_name='포스트',
        related_name='comments',
    )
    author = models.ForeignKey(
        # 'members.User',
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        verbose_name='작성자',
    )
    content = models.TextField()
    tags = models.ManyToManyField(
        'HashTag',
        blank=True,
        verbose_name='해시태그 목록'
    )

    # Comment의 save()가 호출 될 때,
    # content의 값을 사용해서 이 필드를 자동으로 채운 후 저장하기
    _html = models.TextField('태그가 HTML화된 댓글 내용', blank=True)

    class Meta:
        verbose_name = '댓글'
        verbose_name_plural = f'{verbose_name} 목록'

    def save(self, *args, **kwargs):
        def save_html():
            self._html = re.sub(
                self.TAG_PATTERN,
                r'<a href="/explore/tags/\g<tag>/">#\g<tag></a>',
                self.content,
            )

        def save_tags():
            tags = [HashTag.objects.get_or_create(name=name)[0]
                    for name in re.findall(self.TAG_PATTERN, self.content)]
            self.tags.set(tags)

        save_html()
        super().save(*args, **kwargs)
        save_tags()
    @property
    def html(self):
        return self._html


class HashTag(models.Model):
    name = models.CharField('태그명', max_length=100, unique=True,)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '해시태그'
        verbose_name_plural = f'{verbose_name} 목록'


class PostLike(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return 'Post[{post_pk}] Like (User: {username})'.format(
            post_pk=self.post.pk,
            username=self.user.username,
        )

    class Meta:
        # 특정 User가 특정 Post를 좋아요 누른 정보는 unique해야함
        unique_together = (
            ('post', 'user'),
        )

app/posts/forms.py
from django import forms

from .models import Post, Comment


class PostCreateForm(forms.Form):
    photo = forms.ImageField(
        widget=forms.FileInput(
            # HTML위젯의 속성 설정
            # form-control-file클래스를 사용
            attrs={
                'class': 'form-control-file',
           }
        )
    )
    comment = forms.CharField(
        # 반드시 채워져 있을 필요는 없음
        required=False,
        # HTML랜더링 위젯으로 textarea를 사용
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
            }
        ),
    )

    def save(self, **kwargs):
        post = Post.objects.create(
            photo=self.cleaned_data['photo'],
            **kwargs,
        )
        comment_content = self.cleaned_data.get('comment')
        if comment_content:
            # Comment.objects.create(
            #     post=post,
            #     author=post.author,
            #     content=comment_content,
            # )
            post.comments.create(
                author=post.author,
                content=comment_content,
            )

        # 1. Post생성시 Comment생성 (선택적)
        # 만약에 comment항목이 있다면
        # 생성한 Post에 연결되는 Comment를 생성
        #  author=생성한 Post의 author와 동일
        #  post=생성한 Post

        # 2. post_list에서 각 Post에 댓글 목록을 출력
        return post


class CommentCreateForm(forms.Form):
    content = forms.CharField(
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'rows': 2,
            }
        )
    )

    def save(self, post, **kwargs):
        content = self.cleaned_data['content']
        return post.comments.create(
            content=content,
            **kwargs,
        )


class PostForm(forms.ModelForm):
    comment = forms.CharField(
        label='내용',
        required=False,
        widget=forms.Textarea(
            attrs={
                'class': 'form-control',
                'rows': 2,
            }
        )
    )

    # 1. posts.views.post_create
    # 2. templates/posts/post_create.html

    class Meta:
        model = Post
        fields = [
            'photo',
        ]
        widgets = {
            'photo': forms.ClearableFileInput(
                attrs={
                    'class': 'form-control-file',
                }
            )
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'content',
        ]
        widgets = {
            'content': forms.Textarea(
                attrs={
                    'class': 'form-control',
                    'rows': 2,
                }
            )
        }

app/posts/views.py
import re

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from .models import Post, Comment, HashTag
from .forms import PostCreateForm, CommentCreateForm, CommentForm, PostForm


def post_list(request):
    # 1. Post모델에
    #   created_at (생성시간 저장)
    #   modified_at (수정시간 저장)
    #     두 필드를 추가

    # 2. Post모델이 기본적으로 pk 내림차순으로 정렬되도록 설정
    # 3. 모든 Post객체에 대한 QuerySet을
    #    render의 context인수로 전달 (키 : posts)

    # 4. posts/post_list.html을 Template으로 사용
    #       템플릿에서는 posts값을 순회하며
    #       각 Post의 photo정보를 출력

    posts = Post.objects.all()
    context = {
        'posts': posts,
        'comment_form': CommentForm(),
    }
    return render(request, 'posts/post_list.html', context)


@login_required
def post_create(request):
    context = {}
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()

            comment_content = form.cleaned_data['comment']
            if comment_content:
                post.comments.create(
                    author=request.user,
                    content=comment_content,
                )
            return redirect('posts:post-list')

    else:
        form = PostForm()

    context['form'] = form
    return render(request, 'posts/post_create.html', context)


def comment_create(request, post_pk):
    """
    post_pk에 해당하는 POST에 댓글을 생성하는 view
    'POST'메서드 요청만 처리

    'content'키로 돌아온 값을 사용해 댓글 생성. 작성자는 요청한 User
    URL: /posts/<post_pk>/comments/create/

    :param request:
    :param post_pk:
    :return:
    """

    # 1. post_pk에 해당하는 Post객체를 가져와 post변수에 할당
    # 2. request.POST에 전달된 'content'키의 값을 content변수에 할당
    # 3. Comment생성
    #     author: 현재 요청의 user
    #     post: post_pk에 해당하는 Post객체
    #     content: request.POST로 전달된 'content'키의 값
    # 4. posts:post-list로 redirect하기
    if request.method == 'POST':
        post = Post.objects.get(pk=post_pk)
        form = CommentForm(request.POST)
        if form.is_valid():
            # form.save(
            #     post=post,
            #     author=request.user,
            # )
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()

            # comment가 가진 content속성에서
            # 해시태그에 해당하는 문자열들을 가져와서
            # HashTag객체를 가져오거나 생성(get_or_create)
            # 이후 comment.tags에 해당 객체들을 추가

            # 댓글 저장 후, content에 포함된 HashTag목록을 댓글의 tags속성에 set

            return redirect('posts:post-list')


def tag_post_list(request, tag_name):
    posts = Post.objects.filter(comments__tags__name=tag_name).distinct()
    context = {
        'posts': posts,
    }
    return render(request, 'posts/tag_post_list.html', context)


def tag_search(request):
    search_keyword = request.GET.get('search_keyword')
    substituted_keyword = re.sub(r'#|\s+', '', search_keyword)
    return redirect('tag-post-list', substituted_keyword)


@login_required
def post_like_toggle(request, post_pk):
    post = get_object_or_404(Post, pk=post_pk)
    post.like_toggle(request.user)
    url = reverse('posts:post-list')
    return redirect(url + f'#post-{post_pk}')

app/templates/posts/post_create.html
{% extends 'base.html' %}

{% block content %}
<div>
    <h2>포스트 추가</h2>
    <form action="" enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {% for field in form %}
        <div class="form-group">
            <label for="{{ filed.id_for_label }}">{{ field.label }}</label>
            {{ field }}
        </div>
        {% endfor %}
        <button class="btn btn-primary btn-block">업로드</button>
    </form>
</div>
{% endblock %}

app/templates/posts/post_list.html
{% extends 'base.html' %}

{% block content %}
<div>
    {% for post in posts %}
    <!--이 div가 lg(width >= 992px)일 때, 4/12의 크기를 가지며 4/12 위치를 기준으로 시작함-->
    <div id="post-{{ post.pk }}" class="col col-lg-4 offset-lg-4 mb-4">
        <!--Card모양에 대해 미리 정의된 클래스-->
        <div class="card">
            <!--작성자 정보를 나타낼 header부분-->
            <div class="card-header">
{#                <div style="width: 30px; height: 30px; display: inline-block; vertical-align:  middle;">#}
{#                    <a href="#"  style="background-image: url('{{ post.author.img_profile.url }}');#}
{#                                        display: inline-block;#}
{#                                        width: 100%; height: 100%;#}
{#                                        background-size: cover;#}
{#                                        background-position: center center;#}
{#                                        vertical-align: middle;#}
{#                                        margin-right: 10px;"#}
{#                                        class="rounded-circle"></a>#}
{#                </div>#}
                <span>
                    <a href="#">
                        <img src="{{ post.author.img_profile_url }}" style="width: 30px; height: 30px; border-radius: 100%;">
                    </a>
                </span>
                {{ post.author }}
            </div>
            <!--Card의 본문 부분-->
            <div class="card-body">
              <img src="{{ post.photo.url }}" class="card-img-top">
            {% if user.is_authenticated %}

                <form action="{% url 'posts:post-like-toggle' post_pk=post.pk %}">
                    {% csrf_token %}
                    <button class="btn btn-primary" type="submit">
                        {% if user in post.like_users.all %}
                          좋아요 해제
                        {% else %}
                          좋아요
                        {% endif %}
                    </button>
                </form>
{#                버튼의 텍스트에 현재 user가 이 Post에 좋아요를 누른상태라면 '좋아요해제'출력  #}
{#                버튼 클릭시 post_like_toggle에서 해당 로직 처리  #}
            {% endif %}
              <div>
                  <span>좋아하는 사람</span>
                  <strong>{{ post.like_users.all|join:", " }}</strong>
              </div>

              <ul class="list-unstyled">
                  {% for comment in post.comments.all %}
                  <li>
                      <strong>{{ comment.author }}</strong>
                      <span>{{ comment.html|safe }}</span>
                  </li>
                  {% endfor %}
              </ul>
                {% if user.is_authenticated %}
                <form action="{% url 'posts:comment-create' post_pk=post.pk %}" method="POST">
                    {% csrf_token %}
                    {{ comment_form.content }}
                    <button class="btn btn-primary btn-block" type="submit">작성</button>
                </form>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

app/templates/posts/tag_post_list.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
    {% for post in posts %}
    <div class="col-4">
        <div class="row square">
            <a href="#" class="thumbnail" style="background-image: url('{{ post.photo.url }}');"></a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}